modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/sokcuri/naraechat/issues"
license="GNU Lesser General Public License v3.0"
[[mods]]
modId="naraechat"
version="${file.jarVersion}"
displayName="Narae Chat"
updateJSONURL="https://raw.githubusercontent.com/sokcuri/naraechat/master/data/update.json"
displayURL="https://github.com/sokcuri/naraechat"
authors="sokcuri"
description="나래챗은 마인크래프트 한글 입력을 도와줍니다. by 소쿠릿"

[[dependencies.naraechat]] #
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naraechat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
